kind: llm
spec:
  name: ollama-llm
  type: ollama
  config:
    model_name: gpt-oss:20b
    temperature: 0.7
    max_completion_tokens: 4096
    seed: 12345

---
kind: agent
spec:
  name: ReAct-agent
  type: react
  config:
    llm: ollama-llm
    instruction: You are an agent for financial analysis. If you need to calculate the result, you can use the calculator tool.
    max_iterations: 20
    summarize_tool_response: false
    servers:
      - name: yfinance
      - name: calculator

---
kind: benchmark
spec:
  description: Financial Analysis with gpt-oss:20b
  agent: ReAct-agent
  tasks:
    - test/financial_analysis/yfinance_task_0001.json
    - test/financial_analysis/yfinance_task_0002.json
    - test/financial_analysis/yfinance_task_0003.json
    - test/financial_analysis/yfinance_task_0004.json
    - test/financial_analysis/yfinance_task_0005.json
    - test/financial_analysis/yfinance_task_0006.json
    - test/financial_analysis/yfinance_task_0007.json
    - test/financial_analysis/yfinance_task_0008.json
    - test/financial_analysis/yfinance_task_0009.json
    - test/financial_analysis/yfinance_task_0010.json
    - test/financial_analysis/yfinance_task_0011.json
    - test/financial_analysis/yfinance_task_0012.json
    - test/financial_analysis/yfinance_task_0013.json
    - test/financial_analysis/yfinance_task_0014.json
    - test/financial_analysis/yfinance_task_0015.json
    - test/financial_analysis/yfinance_task_0016.json
    - test/financial_analysis/yfinance_task_0017.json
    - test/financial_analysis/yfinance_task_0018.json
    - test/financial_analysis/yfinance_task_0019.json
    - test/financial_analysis/yfinance_task_0020.json
    - test/financial_analysis/yfinance_task_0021.json
    - test/financial_analysis/yfinance_task_0022.json
    - test/financial_analysis/yfinance_task_0023.json
    - test/financial_analysis/yfinance_task_0024.json
    - test/financial_analysis/yfinance_task_0025.json
    - test/financial_analysis/yfinance_task_0026.json
    - test/financial_analysis/yfinance_task_0027.json
    - test/financial_analysis/yfinance_task_0028.json
    - test/financial_analysis/yfinance_task_0029.json
    - test/financial_analysis/yfinance_task_0030.json
    - test/financial_analysis/yfinance_task_0031.json
    - test/financial_analysis/yfinance_task_0032.json
    - test/financial_analysis/yfinance_task_0033.json
    - test/financial_analysis/yfinance_task_0034.json
    - test/financial_analysis/yfinance_task_0035.json
    - test/financial_analysis/yfinance_task_0036.json
    - test/financial_analysis/yfinance_task_0037.json
    - test/financial_analysis/yfinance_task_0038.json
    - test/financial_analysis/yfinance_task_0039.json
    - test/financial_analysis/yfinance_task_0040.json
