kind: llm
spec:
  name: ollama-llm
  type: ollama
  config:
    model_name: deepseek-r1:14b
    temperature: 0.6
    max_completion_tokens: 4096
    seed: 12345

---
kind: agent
spec:
  name: ReAct-agent
  type: react
  config:
    llm: ollama-llm
    system_prompt: /scratch/yp2693/NLP_MCP_AGENTS/ossmcpuniverse/prompts/react_reasoning_prompt.j2
    instruction: You are an agent for repository management.
    max_iterations: 20
    summarize_tool_response: false

---
kind: benchmark
spec:
  description: Repository Management with deepseek-r1:14b
  agent: ReAct-agent
  tasks:
    - test/repository_management/github_task_0001.json
    - test/repository_management/github_task_0002.json
    - test/repository_management/github_task_0003.json
    - test/repository_management/github_task_0004.json
    - test/repository_management/github_task_0005.json
    - test/repository_management/github_task_0006.json
    - test/repository_management/github_task_0007.json
    - test/repository_management/github_task_0008.json
    - test/repository_management/github_task_0009.json
    - test/repository_management/github_task_0010.json
    - test/repository_management/github_task_0011.json
    - test/repository_management/github_task_0012.json
    - test/repository_management/github_task_0014.json
    - test/repository_management/github_task_0015.json
    - test/repository_management/github_task_0016.json
    - test/repository_management/github_task_0017.json
    - test/repository_management/github_task_0018.json
    - test/repository_management/github_task_0019.json
    - test/repository_management/github_task_0021.json
    - test/repository_management/github_task_0022.json
    - test/repository_management/github_task_0023.json
    - test/repository_management/github_task_0024.json
    - test/repository_management/github_task_0025.json
    - test/repository_management/github_task_0026.json
    - test/repository_management/github_task_0027.json
    - test/repository_management/github_task_0028.json
    - test/repository_management/github_task_0029.json
    - test/repository_management/github_task_0030.json
    - test/multi_server/multi-server_task_playwright_github_0001.json
    - test/multi_server/multi-server_task_playwright_github_0002.json
    - test/multi_server/multi-server_task_playwright_github_0003.json
    - test/multi_server/multi-server_task_playwright_github_0004.json
    - test/multi_server/multi-server_task_playwright_github_0005.json
